Issue9 multiparametertest and issue16 h2s-test
nodc-sweden/ocean-data-qc pull request #66
Opened 2024-10-21 14:20 UTC by LenaSMHI

- vi har lagt till två test, ConsistencyCheck och H2sCheck och även ändrat lite i beteendet för DetectionLimitCheck.
- vi ändrade hur testerna loopas i fyskemqc.py för att få samma ordning som när QC_CATEGORIES skapas
- lite smått och gott, ljusfärg t.ex. på probably good :)

Vi vill göra en release av detta när det ser ok ut och sedan peka på den i qc-tool.

2024-10-21 14:44 UTC, jonatanmindroad requested changes
Saknar tester för nya testerna.

2024-10-21 14:44 UTC, jonatanmindroad commented on src/ocean_data_qc/fyskem/configs/consistency_check.yaml
> +#     lower_deviation: 0
Checka inte in utkommenterad kod. Går utmärkt att stoppa i en issue istället.

2024-10-21 14:44 UTC, jonatanmindroad commented on src/ocean_data_qc/fyskemqc.py
> +# vi vill styra testordning så att vi är säkra på att ordningen.
Jag rekommenderar att lägga den här sortens information i en issue istället för inne i koden.

2024-10-21 14:44 UTC, jonatanmindroad commented on src/ocean_data_qc/fyskem/qc_flag_tuple.py
> +    # här kanske också kan kontrolleras att testen gör i ordningen nedan?
Jag rekommenderar att lägga den här sortens information i en issue istället för inne i koden.

2024-10-21 15:30 UTC, LenaSMHI commented on src/ocean_data_qc/fyskem/configs/consistency_check.yaml
> +#     lower_deviation: 0
okejdå [lagt till här](https://github.com/nodc-sweden/ocean-data-qc/issues/67#issue-2602915750)

2024-10-21 15:36 UTC, LenaSMHI commented on src/ocean_data_qc/fyskemqc.py
> +# vi vill styra testordning så att vi är säkra på att ordningen.
fixat [issue](https://github.com/nodc-sweden/ocean-data-qc/issues/68)

2024-10-24 11:48 UTC, jonatanmindroad approved these changes

2024-10-24 15:39 UTC, merged